#!/usr/bin/env python3
"""Build the English dynamic showcase from the reviewed Chinese source deck.

The English deck intentionally shares the exact HTML/CSS/JS interaction model with
the Chinese deck.  Keeping one structural source prevents the two public routes
from drifting while the replacement table makes every audience-facing string
reviewable in one small, deterministic file.
"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "site"


# Longest strings first prevents a shorter phrase from consuming part of a more
# useful sentence.  These are presentation copy only; file names, code values and
# product names remain unchanged where they are meaningful identifiers.
TRANSLATIONS = {
    "数契 ContextOx Demo 1.0.0：从三个不同答案开始，讲清业务定义如何形成、数契与同类工具的区别，以及如何联系体验": "ContextOx Demo 1.0.0: start with three answers, clarify how a business definition forms, compare ContextOx with adjacent tools, and see how to try it",
    "同一句需求形成三份不同结果": "One request produces three different results",
    "从资料到候选定义的可回读链路": "Traceable path from sources to candidate definition",
    "企业数据平台和问数工具的适用场景对比": "Comparison of where general Agents, enterprise data platforms and BI tools fit",
    "选择资料并输入目标的讲解模拟": "Walk-through simulation for selecting sources and entering a goal",
    "三个可能的答案": "three possible answers",
    "三个答案": "Three answers",
    "三个答案怎么算": "How the three answers are calculated",
    "不同工具解决什么问题": "What different tools solve",
    "人确认规则": "Human confirms rules",
    "候选定义更新": "Candidate definition updates",
    "可以回看和交接": "Review and hand off",
    "当前能力与边界": "Capabilities and boundaries",
    "体验数契": "Try ContextOx",
    "规则没有说清": "The rule is unclear",
    "选择资料": "Select sources",
    "提出问题": "Ask questions",
    "讲清业务定义如何形成": "clarify how a business definition forms",
    "数契与同类工具的区别": "compare ContextOx with adjacent tools",
    "数契与通用": "ContextOx and general",
    "Atlan、DataHub": "Atlan, DataHub",
    "数契做什么": "What ContextOx does",
    "业务定义": "business definition",
    "业务事实": "business facts",
    "同一份订单数据": "the same order data",
    "同一份数据": "one dataset",
    "元": "CNY",
    "数契动态介绍": "ContextOx dynamic product introduction",
    "一个真实数字问题 · 公开合成数据": "A real question about numbers · public synthetic data",
    "同一份订单数据，": "The same order data,",
    "为什么会有": "why does it have",
    "三个答案？": "three answers?",
    "所有记录都相加": "add every record",
    "只统计已支付": "count paid orders only",
    "已支付再扣退款": "paid minus refunds",
    "三个数都能算出来。真正没说清的是，哪些算进去、怎么处理、按什么时间。": "All three numbers can be calculated. What is missing is the rule: what counts, how refunds are handled, and which time to use.",
    "数契 ContextOx · Demo 1.0.0": "数契 ContextOx · Demo 1.0.0",
    "01 / 三个答案怎么算": "01 / How the three answers are calculated",
    "同一份数据，三种算法": "One dataset, three calculations",
    "下面 6 行订单全部来自公开合成示例。先看数据，再看每种规则怎样改变华东金额。": "These six orders are from the public synthetic example. First see the rows, then see how each rule changes the East China total.",
    "公开合成数据": "Public synthetic data",
    "订单": "Order",
    "地区": "Region",
    "金额": "Amount",
    "状态": "Status",
    "华东": "East China",
    "华南": "South China",
    "地区由": "Region comes from",
    "连接客户表得到": "joining the customers table",
    "算法 A · 全部相加": "Calculation A · add all records",
    "689 元": "689 CNY",
    "算法 B · 只算 paid": "Calculation B · paid only",
    "440 元": "440 CNY",
    "算法 C · paid 再扣 refunded": "Calculation C · paid minus refunded",
    "390 元": "390 CNY",
    "02 / 为什么总在返工": "02 / Why the rework keeps coming back",
    "公式会写，规则还在每个人脑子里": "The formula is easy; the rule is still in everyone's head",
    "“按地区统计订单金额”听起来已经很清楚。真正开始做时，三个人可能各自补上一套没有写下来的规则。": "“Report order amounts by region” sounds clear. Once work starts, three people may silently fill in three different rules.",
    "一句需求": "One request",
    "按地区统计订单金额": "Report order amounts by region",
    "业务": "Business",
    "把待支付也算进去": "Include pending orders",
    "分析师": "Analyst",
    "只看已支付订单": "Look at paid orders only",
    "财务": "Finance",
    "已支付还要扣退款": "Subtract refunds from paid",
    "最后的问题": "The question left behind",
    "谁算错了？依据在哪里？下次还用哪套？": "Who is wrong? Where is the evidence? Which rule should we use next time?",
    "数契 ContextOx": "数契 ContextOx",
    "先把业务意思说清楚，": "Make the business meaning clear,",
    "再开始交付": "before delivery starts",
    "把资料放进来，说出你想弄清楚的问题": "Bring the sources in and say what you need to understand",
    "Agent 找出处，把会改变结果的问题问出来": "The Agent finds evidence and asks about rules that could change the result",
    "人确认关键规则，留下可以回看的候选定义": "A person confirms the key rules and leaves a candidate definition that can be revisited",
    "Agent 找证据 · 人确认业务事实": "Agent finds evidence · people confirm business facts",
    "03 / 第一步": "03 / Step one",
    "告诉它，这次看哪些资料": "Tell it which sources to use this time",
    "资料范围先说清，Agent 才知道这一轮可以依据什么。": "Set the source boundary first, so the Agent knows what this round can rely on.",
    "讲解模拟 · 对应当前 Workbench": "Walk-through simulation · mirrors the current Workbench",
    "数契": "数契",
    "新对话": "New conversation",
    "资料库": "Sources",
    "本轮已选 3 份资料": "3 sources selected for this round",
    "当前进度": "Current progress",
    "从一个问题开始": "Start with one question",
    "1 明确目标": "1 Set the goal",
    "2 理解资料": "2 Understand sources",
    "3 澄清规则": "3 Clarify rules",
    "4 整理成果": "4 Organize the result",
    "正在做什么": "What is happening",
    "等待你的目标": "Waiting for your goal",
    "需要你做什么": "What we need from you",
    "说出想弄清楚的问题": "Say what you want to understand",
    "已经得到什么": "What we have",
    "3 份资料进入本轮": "3 sources are in this round",
    "任务工作区": "Task workspace",
    "资料已经选好": "Sources are selected",
    "订单、客户和说明文档会一起进入这一轮分析。": "Orders, customers and the notes will enter this analysis together.",
    "数契 Agent": "ContextOx Agent",
    "一起把问题弄清楚": "Work through the question together",
    "你想从这三份资料里弄清什么？": "What do you want to understand from these three sources?",
    "我想按地区统计订单金额。": "I want to report order amounts by region.",
    "资料 · 3": "Sources · 3",
    "发送": "Send",
    "04 / 第二步": "04 / Step two",
    "Agent 把会改变结果的问题问出来": "The Agent asks the questions that can change the result",
    "它不替你猜业务事实。每个问题都会说明，为什么现在需要确认。": "It does not guess business facts for you. Each question explains why it needs an answer now.",
    "讲解模拟 · 公开合成资料": "Walk-through simulation · public synthetic sources",
    "资料里已经找到": "Already found in the sources",
    "订单状态：": "Order status: ",
    "连接字段：": "Join fields: ",
    "orders.customer_id 和 customers.customer_id": "orders.customer_id and customers.customer_id",
    "时间字段：": "Time field: ",
    "paid_at，未支付订单为空": "paid_at; pending orders are empty",
    "待支付订单要算进去吗？": "Should pending orders count?",
    "它会决定华东的 199 元是否进入结果。": "This decides whether the East China 199 CNY enters the result.",
    "影响统计范围": "Changes the population",
    "退款订单怎么处理？": "How should refunds be handled?",
    "排除退款和从已支付金额中扣除，会得到不同答案。": "Excluding refunds and subtracting them from paid amounts produce different answers.",
    "影响金额规则": "Changes the amount rule",
    "按哪个时间归属？": "Which time should assign the order?",
    "资料里有支付时间，退款和待支付记录需要另行说明。": "The sources have payment time; refunds and pending records need a separate rule.",
    "影响时间范围": "Changes the time window",
    "05 / 第三步": "05 / Step three",
    "人用大白话做决定": "A person makes the decision in plain language",
    "Agent 把回答整理成规则，人先核对，再让它进入下一轮。": "The Agent turns the answers into rules. A person checks them before the next round.",
    "讲解模拟 · 人确认以后才采用": "Walk-through simulation · used only after human confirmation",
    "等待确认": "Awaiting confirmation",
    "我把你的回答整理成了 3 条规则": "I organized your answers into 3 rules",
    "请确认下面的文字准确表达了你的意思。": "Please confirm that the wording below matches your meaning.",
    "确认后会更新": "After confirmation, update",
    "地区净订单金额": "Net order amount by region",
    "订单与客户关系": "Order–customer relationship",
    "纳入哪些订单": "Which orders count",
    "只统计已支付订单": "Count paid orders only",
    "pending 不进入金额": "Pending does not enter the amount",
    "退款怎么处理": "How refunds are handled",
    "从原订单地区的已支付金额中扣除": "Subtract from paid amount in the original order region",
    "refunded 作为扣减项": "Treat refunded as a deduction",
    "按哪个时间": "Which time to use",
    "按支付时间归属": "Assign by payment time",
    "未支付订单没有支付时间": "Pending orders have no payment time",
    "修改回答": "Edit answer",
    "确认并继续": "Confirm and continue",
    "06 / 回答带来的变化": "06 / What the answers change",
    "回答之后，定义真的变了": "After the answers, the definition really changes",
    "数契没有把 390 元冒充计算结果。它先把以后该怎样计算写成可以核对的候选定义。": "ContextOx does not present 390 CNY as a computed result. It first writes down a candidate definition for how to calculate it later.",
    "讲解模拟 · 候选成果": "Walk-through simulation · candidate result",
    "本轮更新": "Updated this round",
    "按客户地区汇总已支付金额，再扣除同一地区的退款金额。": "Aggregate paid amounts by customer region, then subtract refunds from that same region.",
    "个字段候选": "candidate field",
    "条关系候选": "candidate relationship",
    "条已确认规则": "confirmed rules",
    "纳入范围": "Included records",
    "已确认": "Confirmed",
    "退款处理": "Refund handling",
    "从原订单地区金额中扣除": "Subtract from the original order region amount",
    "时间归属": "Time assignment",
    "paid_at · 北京时间": "paid_at · China Standard Time",
    "资料关系": "Source relationship",
    "有出处": "Evidence linked",
    "notes.md · 第 7 行：纳入状态、退款和时间需要业务确认": "notes.md · line 7: inclusion, refunds and time need business confirmation",
    "07 / 留下来的工作记录": "07 / The record left behind",
    "留下的不只是一段 AI 回复": "What remains is more than an AI reply",
    "资料、问题、人的回答和候选结果各自保留。换个人接手，也能知道结论从哪里来，还有什么没解决。": "Sources, questions, human answers and the candidate result are kept separately. A new owner can see where the conclusion came from and what is still open.",
    "本轮资料": "Sources this round",
    "3 份公开合成文件": "3 public synthetic files",
    "为什么追问": "Why we asked",
    "哪些选择会改变结果": "Which choices change the result",
    "谁做了决定": "Who decided",
    "人的回答与确认": "Human answer and confirmation",
    "这一轮改了什么": "What changed this round",
    "字段、关系和规则": "Fields, relationships and rules",
    "还不知道什么": "What is still unknown",
    "未知事项继续保留": "Open items stay visible",
    "复核时不用重猜": "Review without guessing again",
    "出处、回答和变化都能沿着同一条记录往回看": "Evidence, answers and changes can be traced through the same record",
    "08 / 适用场景": "08 / Where it fits",
    "不同工具解决不同阶段的问题": "Different tools solve different stages",
    "数契聚焦业务定义还没说清的阶段。它不替代通用 Agent、企业数据平台或问数工具。": "ContextOx focuses on the stage where the business definition is still unclear. It does not replace general Agents, enterprise data platforms or BI tools.",
    "按任务选择": "Choose by task",
    "当你想做什么": "What you want to do",
    "更适合的工具": "A better-fit tool",
    "数契的位置": "ContextOx's place",
    "完成代码、研究或制作任务": "Complete coding, research or making work",
    "通用 Agent，如 Codex": "General Agent, such as Codex",
    "业务定义明确以后，可以继续交给它执行": "Once the business definition is clear, hand execution to it",
    "建设目录、血缘、权限和企业上下文": "Build catalogs, lineage, permissions and enterprise context",
    "未来可以对接，不重复建设企业数据底座": "Can be connected later; no need to rebuild the enterprise data foundation",
    "在既有语义模型上直接问数": "Ask questions on an existing semantic model",
    "BI 与问数工具": "BI and data-question tools",
    "数契处理规则还没有确定的前一步": "ContextOx handles the step before the rule is settled",
    "一句业务需求有多种理解": "One business request has several possible meanings",
    "数契当前聚焦": "ContextOx focus today",
    "找出缺口，请人确认，留下可复核的候选定义": "Find gaps, ask a person to decide, and leave a reviewable candidate definition",
    "数契当前注重点": "ContextOx's current bet",
    "从一组资料和一个具体争议开始，把会改变结果的问题问给人，再把决定、出处和仍未知的内容留在同一份候选定义里。": "Start with a set of sources and one concrete disagreement. Ask a person about the choices that change the result, then keep the decision, evidence and unknowns in one candidate definition.",
    "怎么理解“优势”": "How to read “advantage”",
    "这是产品选择，不是已经被真实业务验证的绝对优势。后续还要和配置合理的通用 Agent 做同题比较。": "This is a product choice, not an absolute advantage validated in real business. It still needs a like-for-like comparison with a well-configured general Agent.",
    "公开产品定位参考（2026-09-13）：": "Public product-positioning references (2026-09-13): ",
    "09 / Demo 1.0.0": "09 / Demo 1.0.0",
    "现在能做什么，也明确不能做什么": "What it can do now—and what it cannot",
    "当前可以体验": "You can try now",
    "和 Agent 连续对话": "Have a continuous conversation with an Agent",
    "不用先理解复杂运行概念": "No need to learn complex run concepts first",
    "明确本轮资料范围": "Set the source boundary for this round",
    "只依据你选中的公开或本地资料": "Use only the public or local sources you selected",
    "追问并确认关键规则": "Ask about and confirm key rules",
    "人的决定不会被悄悄代替": "Human decisions are not silently replaced",
    "查看候选字段、关系和出处": "Review candidate fields, relationships and evidence",
    "变化和未知事项可以回看": "Changes and unknowns stay reviewable",
    "当前不能这样理解": "Do not interpret it as",
    "候选不等于正式批准": "A candidate is not a formal approval",
    "关键业务定义仍需要人的审核": "Key business definitions still need human review",
    "不会写入生产数据库": "It does not write to production databases",
    "Demo 不执行 SQL 或外部业务写入": "The Demo does not run SQL or external business writes",
    "没有云端多人协作": "There is no cloud multi-user collaboration",
    "当前工作区和状态保存在本机": "The current workspace and state stay on this machine",
    "客户价值仍需真实案例验证": "Customer value still needs real-case validation",
    "工程检查不代替业务效果": "Engineering checks do not replace business outcomes",
    "10 / 联系与体验": "10 / Contact and try it",
    "带一个总对不上的业务口径，": "Bring a business definition that never quite matches,",
    "和数契一起把它说清楚": "and make it clear with ContextOx",
    "可以先用公开合成示例体验，也可以带一组脱敏资料试一轮。": "Start with the public synthetic example, or bring a redacted set of sources for one round.",
    "交流问题或申请体验": "Discuss a question or request a trial",
    "联系 @archerthegoat": "Contact @archerthegoat",
    "播放 45 秒产品演示": "Play the 45-second product film",
    "离线阅读 12 页 PDF": "Read the 12-page PDF offline",
    "查看公开源码": "View the public source",
    "公开源码 · 公开合成 Demo · 候选结果由人核对": "Public source · public synthetic Demo · candidate results checked by people",
    "45 秒演示": "45-second film",
    "减弱动效": "Reduce motion",
    "恢复动效": "Restore motion",
    "全屏": "Fullscreen",
    "目录": "Contents",
    "页面目录": "Page contents",
    "演示控制": "Presentation controls",
    "上一页": "Previous slide",
    "下一页": "Next slide",
    "01 · 三个答案": "01 · Three answers",
    "02 · 三种算法": "02 · Three calculations",
    "03 · 规则没有说清": "03 · The rule is unclear",
    "04 · 数契做什么": "04 · What ContextOx does",
    "05 · 选择资料": "05 · Select sources",
    "06 · Agent 提出问题": "06 · Agent asks",
    "07 · 人确认规则": "07 · Human confirms",
    "08 · 候选定义更新": "08 · Candidate definition updates",
    "09 · 可以回看和交接": "09 · Review and hand off",
    "10 · 不同工具的分工": "10 · Different tool roles",
    "11 · 当前能力与边界": "11 · Capabilities and boundaries",
    "12 · 联系与体验": "12 · Contact and try",
    "数契标志": "ContextOx mark",
    "数契项目动态介绍": "ContextOx project dynamic introduction",
}


def translate(source: str) -> str:
    output = source
    for chinese, english in sorted(TRANSLATIONS.items(), key=lambda item: len(item[0]), reverse=True):
        output = output.replace(chinese, english)
    output = output.replace('lang="zh-CN"', 'lang="en"')
    output = output.replace("<title>数契动态介绍</title>", "<title>ContextOx dynamic product introduction</title>")
    output = output.replace(
        'content="数契 ContextOx Demo 1.0.0：从三个不同答案开始，讲清业务定义如何形成、数契与同类工具的区别，以及如何联系体验"',
        'content="ContextOx Demo 1.0.0: start with three answers, clarify business definitions, compare tool roles, and see how to try it"',
    )
    output = output.replace(
        '<main class="deck" aria-label="数契项目动态介绍">',
        '<main class="deck" aria-label="ContextOx project dynamic introduction">',
    )
    output = re.sub(r'<p class="slide__kicker">10 / 适用场景</p>', '<p class="slide__kicker">08 / Where it fits</p>', output)
    # The source has a dedicated language link marker so the two routes remain
    # one click apart without relying on browser locale detection.
    output = output.replace(
        '<a class="language-link" href="presentation-en.html#1" lang="en">English</a>',
        '<a class="language-link" href="presentation.html#1" lang="zh-CN">Chinese</a>',
    )
    output = output.replace(
        "downloads/contextox-demo-1.0.0-product-film.mp4",
        "downloads/contextox-demo-1.0.0-product-film-en.mp4",
    )
    output = output.replace(
        "downloads/contextox-demo-1.0.0-presentation.pdf",
        "downloads/contextox-demo-1.0.0-presentation-en.pdf",
    )
    return output


def main() -> None:
    source = (SITE / "presentation.html").read_text(encoding="utf-8")
    translated = translate(source)
    # The brand name is intentionally bilingual; all other CJK copy should have
    # a deterministic translation before the artifact is published.
    remaining = set(re.findall(r"[\u4e00-\u9fff]+", translated)) - {"数契"}
    if remaining:
        raise SystemExit(f"untranslated CJK copy remains: {sorted(remaining)}")
    (SITE / "presentation-en.html").write_text(translated, encoding="utf-8")
    print("wrote site/presentation-en.html")


if __name__ == "__main__":
    main()
